/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DiariesRouteImport } from './routes/diaries'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as DiariesIndexRouteImport } from './routes/diaries.index'
import { Route as DiariesNewRouteImport } from './routes/diaries.new'
import { Route as DiariesDiaryIdRouteImport } from './routes/diaries.$diaryId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariesRoute = DiariesRouteImport.update({
  id: '/diaries',
  path: '/diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariesIndexRoute = DiariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiariesRoute,
} as any)
const DiariesNewRoute = DiariesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DiariesRoute,
} as any)
const DiariesDiaryIdRoute = DiariesDiaryIdRouteImport.update({
  id: '/$diaryId',
  path: '/$diaryId',
  getParentRoute: () => DiariesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/charts': typeof ChartsRoute
  '/diaries': typeof DiariesRouteWithChildren
  '/signin': typeof SigninRoute
  '/diaries/$diaryId': typeof DiariesDiaryIdRoute
  '/diaries/new': typeof DiariesNewRoute
  '/diaries/': typeof DiariesIndexRoute
}
export interface FileRoutesByTo {
  '/charts': typeof ChartsRoute
  '/signin': typeof SigninRoute
  '/diaries/$diaryId': typeof DiariesDiaryIdRoute
  '/diaries/new': typeof DiariesNewRoute
  '/diaries': typeof DiariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/charts': typeof ChartsRoute
  '/diaries': typeof DiariesRouteWithChildren
  '/signin': typeof SigninRoute
  '/diaries/$diaryId': typeof DiariesDiaryIdRoute
  '/diaries/new': typeof DiariesNewRoute
  '/diaries/': typeof DiariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/charts'
    | '/diaries'
    | '/signin'
    | '/diaries/$diaryId'
    | '/diaries/new'
    | '/diaries/'
  fileRoutesByTo: FileRoutesByTo
  to: '/charts' | '/signin' | '/diaries/$diaryId' | '/diaries/new' | '/diaries'
  id:
    | '__root__'
    | '/charts'
    | '/diaries'
    | '/signin'
    | '/diaries/$diaryId'
    | '/diaries/new'
    | '/diaries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChartsRoute: typeof ChartsRoute
  DiariesRoute: typeof DiariesRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaries': {
      id: '/diaries'
      path: '/diaries'
      fullPath: '/diaries'
      preLoaderRoute: typeof DiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaries/': {
      id: '/diaries/'
      path: '/'
      fullPath: '/diaries/'
      preLoaderRoute: typeof DiariesIndexRouteImport
      parentRoute: typeof DiariesRoute
    }
    '/diaries/new': {
      id: '/diaries/new'
      path: '/new'
      fullPath: '/diaries/new'
      preLoaderRoute: typeof DiariesNewRouteImport
      parentRoute: typeof DiariesRoute
    }
    '/diaries/$diaryId': {
      id: '/diaries/$diaryId'
      path: '/$diaryId'
      fullPath: '/diaries/$diaryId'
      preLoaderRoute: typeof DiariesDiaryIdRouteImport
      parentRoute: typeof DiariesRoute
    }
  }
}

interface DiariesRouteChildren {
  DiariesDiaryIdRoute: typeof DiariesDiaryIdRoute
  DiariesNewRoute: typeof DiariesNewRoute
  DiariesIndexRoute: typeof DiariesIndexRoute
}

const DiariesRouteChildren: DiariesRouteChildren = {
  DiariesDiaryIdRoute: DiariesDiaryIdRoute,
  DiariesNewRoute: DiariesNewRoute,
  DiariesIndexRoute: DiariesIndexRoute,
}

const DiariesRouteWithChildren =
  DiariesRoute._addFileChildren(DiariesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChartsRoute: ChartsRoute,
  DiariesRoute: DiariesRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
